name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:

      - name: checkout sources
        uses: actions/checkout@v2

      - name: install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: build default
        run: cargo build --verbose --release

      #- name: build --feature lib0-serde
      #  run: cargo build --verbose --features lib0-serde

  test-linux:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: test
        run: cargo test --release

  test-macos:
    runs-on: macos-latest
    needs: build
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: test
        run: cargo test --release